### ISSUE TITLE
Is there a way to pull all the language sources together?

### ISSUE THREAD

**Issue by shimizurei** [elarkham/VGMdb-BeetsPlug#2]
I like to organize my music files in the format: 

> ##. Romaji (Kana/Kanji_English)
> Example: 01. Sousou ~WEL ARY TINDHARIA?\~ (創奏 ～WEL ARY TINDHARIA?～_Overture of Creation ~Will You Sing the Song of the World?\~)

Is it possible to build the renaming in a way that if english or japanese are available, I can rename my file in this format? If so, how can it be done?

**Comment by elarkham** [comment]
The language priority for this is Eng -> Romaji -> whatever, if you have different preferences you can change it by tweaking the code [here](https://github.com/elarkham/VGMdb-BeetsPlug/blob/a7e30f3efe5f3141a39f512b6651ec98529643d9/vgmdb.py#L142-L147
). Album names on the other hand use whatever preferred language you have configured with Beets, I forget why I didn't do this for track names. 

I'm currently using this unofficial VGMdb API: http://vgmdb.info/ for the plugin, you can see an example of the language key names here: http://vgmdb.info/album/23631?format=json. VGMdb has different language keys for tracks than they do for Album names, not sure why but keep this in mind. For "Kana/Kanji_English" I think you would just want to do the "Japanese" key, VGMdb was never meant to be used for APIs so sometimes they use rare keys like "Romaji" but it's not very common. This is why you need to make sure to always have some sort of fallback.  

This isn't tested and it's a little messy but for what you desire I think you would want to change it to something like this:
```python
if track["names"].has_key("English") and track["names"].has_key("Japanese"):
    title = track["names"]["English"] + "(" + track["names"]["Japanese"] + ")"
elif track["names"].has_key("Romaji") and track["names"].has_key("Japanese"):
    title = track["names"]["Romaji"] + "(" + track["names"]["Japanese"] + ")"
elif track["names"].has_key("English"):
    title = track["names"]["English"]
elif track["names"].has_key("Romaji"):
    title = track["names"]["Romaji"]
else:
    title = track["names"].values()[0]
```

**Comment by shimizurei** [comment]
Awesome, I'll give it a go. Thanks!
